### ISSUE TITLE
OpenCV installation issue

### ISSUE THREAD

**Issue by sstamatis01** [twhui/LiteFlowNet#1]
First of all great job! However I have an installation error related to opencv

After I run `make -j 8 all tools pycaffe` I get the following error 
`#error "OpenCV 4.x+ requires enabled C++11 support" #  error "OpenCV 4.x+ requires enabled C++11 support"`

My opencv version is 3.2.0, and I have followed your instructions. Do you have any idea what might cause this error and how I can get by? Thank you for your time in advance.

**Comment by twhui** [comment]
Did you enable the opencv 3 flag in Makefile.config?

**Comment by sstamatis01** [comment]
If you are referring to this:
```
# Uncomment if you're using OpenCV 3
OPENCV_VERSION := 3
```
yes I have.

**Comment by twhui** [comment]
My version is 3.1.0. I am unable to duplicate your error.

**Comment by sstamatis01** [comment]
I was hoping it could be something you have encountered before and perhaps provide some insight, but since you dont know of it I will look it on my own. I will close the issue and if I solve it I will add the solution here. Thanks anyway!
