### ISSUE TITLE
resample_layer.hpp missing

### ISSUE THREAD

**Issue by lijiaman** [twhui/LiteFlowNet#10]
Hi, it seems resample_layer.hpp not in layers/ . I met some error about opencv, ReadImagefromMat not declared in the scope. Is current repo not complete to compile successfully? Thanks.

**Comment by twhui** [comment]
resample_layer.hpp is in /liteflownet/src/caffe/layers. It is normal to have warnings but not errors. The current repo should work fine except that the models files are not released.
