### ISSUE TITLE
question about the implementation of 'f-lcon'

### ISSUE THREAD

**Issue by HuangJunJie2017** [twhui/LiteFlowNet#11]
HI:
 
the paper lack of the introduction of the final implement of  'f-lcon', as I can not figure out a proper way to obtain 'f_lcon5_R(flow5_R, N*2*W*H)' from 'softmax5_R(N*9*W*H)' and 'flow5_S(N*2*W*H)'.   Is the implement of 'lcon' introduced in the reference paper 'DeepFace:Closing the gap to human-level performance in face verification.'?

**Comment by HuangJunJie2017** [comment]
in section 3.2   f_g(c) = \~G(c)\odot \~F(c). there is 9 channels in 'softmax5_R' but 2 channels in 'flow5_S'

**Comment by twhui** [comment]
@HuangJunJie2017 The implementation of LiteFlowNet (including f-lcon) is on the prototxt file. I have not uploaded the model files to my github repo yet. Of course, you cannot figure out how to implement this and that. Could you be more patient? CVPR conference has not started yet, right? I will release the missed files well before the CVPR conference.

**Comment by Crow77** [comment]
How do you create de training.list and the test.list from the downloaded dataset (e.g KITTI12) ?
I'm trying to run the make-lmdbs-train.sh script

Please help
