### ISSUE TITLE
‘ReadImageToCVMat’ was not declared in this scope

### ISSUE THREAD

**Issue by lijiaman** [twhui/LiteFlowNet#12]
When compiling, I got this error. Please help! thx! 
src/caffe/layers/imgreader_layer.cpp: In instantiation of ‘void caffe::ImgReaderLayer<Dtype>::ReadData() [with Dtype = double]’:
src/caffe/layers/imgreader_layer.cpp:80:1:   required from here
src/caffe/layers/imgreader_layer.cpp:45:38: error: ‘ReadImageToCVMat’ was not declared in this scope
Makefile:576: recipe for target '.build_release/src/caffe/layers/imgreader_layer.o' failed

**Comment by twhui** [comment]
Did you install opencv?

**Comment by lijiaman** [comment]
yes, I have opecn3.2 in server. And I also set the Opecv in Makefile.

**Comment by lijiaman** [comment]
Solved this issue by removing the #ifdef USE_OPENCV in io.hpp and io.cpp. weird that USE_OPENCV didn't work in Makefile.config. Anyway, thx.
