### ISSUE TITLE
Run and save flo successfully, but the generated "*.flo" are all 'Nan' value

### ISSUE THREAD

**Issue by my1347** [twhui/LiteFlowNet#13]
Run and save flo successfully, but the generated "*.flo" are all 'Nan' value

**Comment by twhui** [comment]
How did you read those .flo files?

**Comment by my1347** [comment]
@twhui 
Using np.fromfile which is the same procedure I used int Flownet2 generated flo files
![image](https://user-images.githubusercontent.com/5409816/41387939-2e0b1db6-6fbc-11e8-8bc7-86fbfc102903.png)

**Comment by twhui** [comment]
@my1347 I used KITTI's matlab toolbox to read it. I don't have such probelm.

**Comment by my1347** [comment]
@twhui Ok, I will try Matlab, thank you buddy

**Comment by my1347** [comment]
@twhui "KITTI's matlab toolbox " or "Sintel's Matlab toolbox"?
