### ISSUE TITLE
Compile error.  tools/convert_imageset_and_flow.cpp:

### ISSUE THREAD

**Issue by ericsqxd** [twhui/LiteFlowNet#14]
When I compile the project, I encountered the error as follow.
tools/convert_imageset_and_flow.cpp:144:27: error: ‘numeric_limits’ is not a member of ‘std’
tools/convert_imageset_and_flow.cpp:144:47: error: expected primary-expression before ‘short’
tools/convert_imageset_and_flow.cpp:144:47: error: expected ‘;’ before ‘short’
Could you help me?

**Comment by twhui** [comment]
@ericsqxd I have not received any reports from other uses to encounter such errors. "error: ‘numeric_limits’ is not a member of ‘std’" This error is related to openCV. Did you install openCV and enable the flag in Makefile.config?

**Comment by twhui** [comment]
closed due to inactivity

**Comment by liangxi627** [comment]
@ericsqxd I installed openCV3.0 and meet the same error, do you solve it?
