### ISSUE TITLE
can you explain what the use of layer "FlowScaling" 

### ISSUE THREAD

**Issue by leonardodora** [twhui/LiteFlowNet#15]
I don't konw why the coeff is set to 0.05. 
also, in the NetE-S: L6, why the coeff is set to 0.625?

thanks for your answers!

**Comment by twhui** [comment]
It is used to scale flow magnitude.

**Comment by leonardodora** [comment]
yes. but I still don't get it that why 0.05 or 0.625. dose it have matter with the resize of the image? and what is the relationship?

**Comment by twhui** [comment]
0.05 = 1/20. This is the regression trick used by FlowNet2.

**Comment by leonardodora** [comment]
ok. thanks!

**Comment by wuwenhuan** [comment]
@sniklaus  Thank you!
