### ISSUE TITLE
the loss of the tranning phase seems falling. But in the test phase, the loss is inf. 

### ISSUE THREAD

**Issue by leonardodora** [twhui/LiteFlowNet#16]
hi, I have trained a part of your model, and the loss of the tranning phase seems falling. But in the test phase, the loss is inf. 
and I saw there is " Testing phase only  " in your prototxt. does them have some relationship? and why you add the " Testing phase only  " part? thanks for your answer!

**Comment by twhui** [comment]
The loss should not be inf. It is rather strange.

If you find any part in my prototxt that is not useful to your application, of course you can remove it.
