### ISSUE TITLE
LiteFlowNetX

### ISSUE THREAD

**Issue by SmartPorridge** [twhui/LiteFlowNet#19]
Hi,
Thank you for your work!

Will you release the train.prototxt of LiteFlowNetX and the solver settings?

Thank you !

**Comment by twhui** [comment]
Hi SmartPorridge,

Thanks for your interest on my work!

LiteFlowNetX is used for the ablation study. It performs not as good as LiteFlowNet. I don't see any strong reasons to release it to the public.

**Comment by SmartPorridge** [comment]
Hi twhui,

From your paper, LiteFlowNetX is much more faster than LiteFlowNet, it's of great importance to me. If it's improper to release it to the public, would you mind send it to me in private.  I want to speed up my project. 
My email : jiqiangzhou@alu.hit.edu.cn 

Thank you for your excellent work.
Best,
Jiqiang
