### ISSUE TITLE
make tools and pycaffe

### ISSUE THREAD

**Issue by HilmiK** [twhui/LiteFlowNet#2]
make command gives the same error for both which is -> make: Nothing to be done for 'pycaffe'.

**Comment by twhui** [comment]
Could you specify your question more clearly?

**Comment by HilmiK** [comment]
It may not require to enter them into command line but when I enter make tools or make pycaffe into bash : "Nothing to be done for "tools" or "pycaffe" comes.

**Comment by twhui** [comment]
Try this one then! "make -j 8 tools pycaffe" (I assume you entered "make clean").
