### ISSUE TITLE
how to train the MPI-Sintel dataset

### ISSUE THREAD

**Issue by XDhughie** [twhui/LiteFlowNet#20]
I don't know how to use the MPI-Sintel dataset to generate the .list docment. Can u tell me how to use this dataset and apply to the liteflownet. thank u!!

**Comment by twhui** [comment]
Each line in a list file contains the file paths for an image pairs and the corresponding ground-truth flow file. e.g. PATH/frame_0001.png PATH/frame_0002.png PATH/frame_0001.flo
