### ISSUE TITLE
Issues during compilation.

### ISSUE THREAD

**Issue by TusharNimbhorkar** [twhui/LiteFlowNet#21]
Hi

When I am compiling by make. I am getting the following error. Most of the caffe stuff gets compiled properly but towards the end, it crashes. 

SS is attached. I am not sure what is wrong. 

Also, Can you tell how much GPU memory the model uses while training? 

![image](https://user-images.githubusercontent.com/6749360/44213360-cd241000-a16d-11e8-8b66-4a76dc3fc012.png)

**Comment by twhui** [comment]
What are your machine settings? I have not received any reports from other users to have such a compilation issue.

I can't remember the exact memory consumption used. A single Titan X should be more than enough.

**Comment by XDhughie** [comment]
hello,Did you run the MPI-Sintel dataset through liteflownet
