### ISSUE TITLE
Data interface

### ISSUE THREAD

**Issue by XDhughie** [twhui/LiteFlowNet#22]
I have downloaded the data and the caffe is configured. But I don't know where the data interface . The script file in the data file requires two list files. Is it by myself to write the program to generate a .list file for the image pair and the .flo file? Thank you!
I first contacted the experiment of optical flow. Can you give a concrete example, thank you?

**Comment by twhui** [comment]
There are many script files. I have no idea which script file you are referring. You need to raise your question more clearly.

**Comment by XDhughie** [comment]
In the /LiteFlowNet-master/data, there is a make-lmdbs-train.sh, and it needs a .list file to generate the lmdb file.I don't know how to use the MPI-Sintel dataset to generate .list file.Is there a detail tutorial.Thank u!!

**Comment by twhui** [comment]
You can write a very simple script to do the task. This should not be very difficult. I leave the task to you.

There should be a README file (or simple description) in the dataset or on the dataset webpage. It tells you how each image pair is associated with the ground-truth file. You need to understand the naming convention and structure of data directory first.
