### ISSUE TITLE
How to get the optical flow value in .flow file?

### ISSUE THREAD

**Issue by liangxi627** [twhui/LiteFlowNet#26]
I have generated the .flo files of my dataset through the pre-trained model. How to get the value (u,v) in the .flo file at pixel location (x,y) in the original frame? Please help me~

**Comment by twhui** [comment]
You can find the I/O scripts (and also visualization tools) from http://vision.middlebury.edu/flow/code/flow-code.zip (C) or http://sintel.is.tue.mpg.de/downloads (C and matlab). There are also python scripts available on other github pages.

**Comment by liangxi627** [comment]
Ok, many thanks.
