### ISSUE TITLE
train/test prototxt

### ISSUE THREAD

**Issue by adamtwig** [twhui/LiteFlowNet#3]
Would you be willing to share the train/test prototxt?

I noticed in the train section we're asked to copy from this directory, which I cannot find:
2. Copy files from <code>LiteFlowNet/models/training_template</code> to a new model folder...

Additionally, in the test script it mentions "deploy.tpl.prototxt", which I also cannot find.

If you could point me in the right direction or share these files, that would be appreciated.

**Comment by twhui** [comment]
All the prototxt files will be available soon.
