### ISSUE TITLE
LiteFlowNet cnn

### ISSUE THREAD

**Issue by sarmadm** [twhui/LiteFlowNet#30]
HI

I need to apply LiteFlowNet on video data and extract flow features to feed it to cnn.

What kind of features can I get from videos and how can I save them for each video file ?

**Comment by Aminullah6264** [comment]
Dear sarmadm,

Do you have script for running video for LiteFlowNet. 
Please share

**Comment by Aminullah6264** [comment]
Dear Sarmadm,

I made script of video and modified the deploy.prototxt, please follow the link.

https://github.com/Aminullah6264/LiteFlowNet-for-Video
