### ISSUE TITLE
network training

### ISSUE THREAD

**Issue by luoru** [twhui/LiteFlowNet#33]
What't the reason for stage-wise training scheme in pre-training procedure. I tried firstly train like flownet2, the NAN loss occured with  Flow Regularization, how to avoid this? appreciate your reply

**Comment by twhui** [comment]
Hi luoru, one reason is faster training. I have not experienced NAN loss. Actually, you can simply use the trained models for your application. If your prefer a higher accuracy, you can consider to use my extended work LiteFlowNet2 (https://github.com/twhui/LiteFlowNet2).
