### ISSUE TITLE
Poor results from gray images with small motion like UCSD

### ISSUE THREAD

**Issue by fjchange** [twhui/LiteFlowNet#34]
I have test the all three model on UCSD dataset, which are gray images. I make them RGB and feed into the model, but get really bad result compared to flownet2.

I visualize the flow as  Baker et al. "A Database and Evaluation Methodology for Optical Flow" (ICCV, 2007) URL: http://vision.middlebury.edu/flow/flowEval-iccv07.pdf, using the code [here](https://github.com/tomrunia/OpticalFlow_Visualization) 
It work well on other RGB dataset like CUHK avenue, which have a larger motion. Is there any wrong I missed or the models are not suitable for gray images or small motion image pairs..

first image
![first image](https://user-images.githubusercontent.com/22427196/54512947-d2aa3880-4990-11e9-8322-c9a6dff53af9.png)

second image
![second image](https://user-images.githubusercontent.com/22427196/54512978-e5bd0880-4990-11e9-81f0-c3fa8d79a32c.png)

sintel reuslt
![sintel result](https://user-images.githubusercontent.com/22427196/54512654-e2754d00-498f-11e9-806c-c845065a7acd.png)

default result
![default result](https://user-images.githubusercontent.com/22427196/54512713-0f296480-4990-11e9-8d29-cc255c043437.png)

kitti result, this seems better but not practical
![kitti result](https://user-images.githubusercontent.com/22427196/54512753-354f0480-4990-11e9-9ee7-1650c7cdd760.png)

while the result from flownet2 much better 
![image](https://user-images.githubusercontent.com/22427196/54512842-7e06bd80-4990-11e9-91e6-2ba7c7e991e9.png)

the number in  .flo are very small, but the visualization tells the failure.

**Comment by twhui** [comment]
I have not tested my models on UCSD. From your provided results, UCSD dataset is quite challenging to both FlowNet and LiteFlowNet. You may have a try on my newer model LiteFlowNet2.

**Comment by twhui** [comment]
You may need to fine-tune LiteFlowNet on small-motion dataset e.g. ChairsSDHom.
