### ISSUE TITLE
Questions about finetuning on Kitti

### ISSUE THREAD

**Issue by deepcharle** [twhui/LiteFlowNet#36]
Thank you for your outstanding work! 
Here is my question about the finetuning process on Kitti. As the network has done many augmentations, note that the groundtruth values in Kitti is very sparse, so how do you implement augmentation during finetuning on Kitti training images? Or do you only skip the augmentation steps?

**Comment by twhui** [comment]
Augmentation is required on KITTI training sets as well. The provided augmentation can handle sparse data.
