### ISSUE TITLE
When I switch off the regularization, the network starts printing augmentation parameters

### ISSUE THREAD

**Issue by ADHARACSM** [twhui/LiteFlowNet#37]
Running the network in testing phase,
When I switch off the regularization for all the losses, the network starts printing augmentation parameters and it takes a very long time to get the output.
Do you have idea why does it happen and how can I stop it?

**Comment by adhara123007** [comment]
When I switched off the layers under 
#######################################
#             NetE-R: L2              #
#######################################

I start getting the following output

![image](https://user-images.githubusercontent.com/40571095/56862370-0de15380-69a2-11e9-95f4-0ce4ea920f50.png)

And it takes a long time to run and I don't get result...

**Comment by twhui** [comment]
I think you have not disabled all the related layers. The screen shot suggests that img0_aug_L2 is not used by other layers. You need to remove img0_aug_L2 as well.

**Comment by adhara123007** [comment]
Had to make changes to the caffe.proto file to stop this
