### ISSUE TITLE
find: ‘examples’: No such file or directory

### ISSUE THREAD

**Issue by CXMANDTXW** [twhui/LiteFlowNet#41]
After downloading the code,I only changed my cuda path in makefile.config, then:
cd LiteFlowNet
make -j 8 tools pycaffe
something wrong happened:
matlab/+caffe/private python/caffe src/gtest src/caffe src/caffe/test src/caffe/layers src/caffe/util src/caffe/proto src/caffe/solvers tools
find: ‘examples’: No such file or directory
find: ‘examples’: No such file or directory
find: ‘examples’: No such file or directory
touch python/caffe/proto/__init__.py
PROTOC src/caffe/proto/caffe.proto
CXX tools/convert_imageset.cpp
~~~~~~
cuda:8.0
cudnn:5.1

could you give me some advice ?

**Comment by twhui** [comment]
This is normal as I removed the folder "examples" in Caffe.
