### ISSUE TITLE
invalid literal for int() with base 10: "b'1241"

### ISSUE THREAD

**Issue by CXMANDTXW** [twhui/LiteFlowNet#42]
I use 'test_iter.py' to test KITTI datasets , model is liteflownet-ft-kitti , and I meet the following error:
Traceback (most recent call last):
  File "test_iter.py", line 96, in <module>
    img1_size = get_image_size(images[0][idx])
  File "test_iter.py", line 15, in get_image_size
    dim_list = [int(dimstr) for dimstr in str(subprocess.check_output([img_size_bin, filename])).split(',')]
  File "test_iter.py", line 15, in <listcomp>
    dim_list = [int(dimstr) for dimstr in str(subprocess.check_output([img_size_bin, filename])).split(',')]
ValueError: invalid literal for int() with base 10: "b'1241"

**Comment by twhui** [comment]
I have no idea why you had such an error. Did you have any problems when you use test_batch,py for Sintel?

**Comment by twhui** [comment]
Closed due to inactivity.

**Comment by thohemp** [comment]
I am facing the same error. Please reopen.  @twhui

**Comment by twhui** [comment]
Reopened @thohemp

**Comment by thohemp** [comment]
Solution:

`import re`

changing
`dim_list = [int(dimstr) for dimstr in str(subprocess.check_output([img_size_bin, filename])).split(',')]`
to
`dim_list = [int(re.sub("\D","",dimstr)) for dimstr in str(subprocess.check_output([img_size_bin, filename])).split(',')]`
