### ISSUE TITLE
Training stopped at level L2

### ISSUE THREAD

**Issue by adhara123007** [twhui/LiteFlowNet#45]
Dear Dr. Tak Wai HUI

Can you please let me know why did you stop at level L2 loss and didn't train the network for full resolution loss (L1 I mean) : 768x384?

Thanks and Regards,
Arnab

**Comment by twhui** [comment]
Hi Arnab, the reason is simply because there is no significant difference on flow accuracy between level 2 and level 1.

**Comment by adhara123007** [comment]
thanks
