### ISSUE TITLE
Why is the resolution of the output of the optical flow inferred with Liteflownet half size of the original image pair?

### ISSUE THREAD

**Issue by wuwenhuan** [twhui/LiteFlowNet#46]
For the Liteflownet, the resolution of the output of the optical flow when inferring with Liteflownet is the half of the original image pair, and then the output is upsampled to the same size as the original image. However, why not directly output the optical flow whose size is the same as the original image? And I notice that PWC-Net also uses the similar manner. Thank you!

**Comment by twhui** [comment]
You can refer to https://github.com/twhui/LiteFlowNet/issues/45

**Comment by wuwenhuan** [comment]
thanks!
