### ISSUE TITLE
How to use code in matlab

### ISSUE THREAD

**Issue by neetutiwarihokkaido** [twhui/LiteFlowNet#47]
I need to use your model in my research using Matlab.
The syntax is to import pre trained CNN models is below
net = importCaffeNetwork(protofile,datafile)
Please check the link below:
https://www.mathworks.com/help/deeplearning/ref/importcaffenetwork.html#bvo3trn-3
These two files need to be in this form
protofile = '.prototxt';
datafile = '.caffemodel';
How to get those files for Matlab or is there any other way I can use it?
Please help me with this issue.

**Comment by twhui** [comment]
I have not tried to run LiteFlowNet in Matlab.

**Comment by neetutiwarihokkaido** [comment]
Can you provide this file:
 protofile = '.prototxt'; here .prototxt file contains the network architecture
I am interested in using your network architecture and slightly modify it according to my case. 
This would be very helpful for my research.

**Comment by twhui** [comment]
You can find the prototxt files in https://github.com/twhui/LiteFlowNet/tree/master/models/

**Comment by twhui** [comment]
closed due to inactivity
