### ISSUE TITLE
Question about data augmentation?

### ISSUE THREAD

**Issue by PeiqinSun** [twhui/LiteFlowNet#52]
hi. (我猜你应该中国人, 因为我看到了香港中文大学.) 首先, 非常感觉你做的工作. 我目前也在研究关于CNN opticalFlow, 我有一些insight想和你讨论一下. 
1. flowNet的数据增广好像特别难以模拟出来, 至少感觉目前这一分支一直沿用caffe框架的原因我猜应该也是这个增广问题吧? 至少, 我用python复现的网络, 都在sintel上达不到原来用caffe训练得到的结果.
2. 网络的一些特殊层真的那么重要吗? 我怎么感觉从我个人的实验来看, 除了残差金字塔的结构有明显作用, correlation和warpLayer的作用感觉并不是特别明显. 

希望能和你讨论一下关于数据增广方面的细节问题, 如果方便, 能否有邮箱交流?

**Comment by twhui** [comment]
I simply used the augmentation layer as FlowNet2. I have not tried other alteratives other than Caffe.

I have no idea why you have such a conclusion. All the proposed components are important for optical flow estimation as presented in the ablation study.

**Comment by Crow77** [comment]
How do you create de training.list and the test.list from the downloaded dataset (e.g KITTI12) ?
I'm trying to run the make-lmdbs-train.sh script

Please help
