### ISSUE TITLE
Data augmentation layers

### ISSUE THREAD

**Issue by abrosua** [twhui/LiteFlowNet#57]
I have some question regarding the data augmentation methods and their parameters.

From my observation, the [LiteFlowNet train prototxt](https://github.com/twhui/LiteFlowNet/blob/7c796e3740c987aed2688943a0dfd1d3c31852d1/models/training_template/train.prototxt.template#L66) (the data augmentation layer and their respective parameters, e.g. translate, rotate, zoom, color, contrast, brightness, etc) is very similar to the [FlowNet train prototxt](https://lmb.informatik.uni-freiburg.de/resources/binaries/dispflownet/dispflownet-release-1.2.tar.gz), instead of the [FlowNet2.0 train prototxt](https://github.com/lmb-freiburg/flownet2/blob/b92e198b56b0e52e1ba0a5a98dc0e39fa5ae70cc/models/download-models.sh#L3).

Just to make sure, did you use the same data augmentation parameters as the one that written in the [FlowNet paper](https://arxiv.org/pdf/1504.06852.pdf)? Because I find it quite hard to understand the caffe's augmentation layer cpp scripts, due to my lack of experiences with caffe.

> Specifically we sample translation from the range [−20%,20%] of the image width for x and y; rotation from [−17, 17]; scaling from [0.9, 2.0]. The Gaussian noise has a sigma uniformly sampled from [0, 0.04]; contrast is sampled within [−0.8, 0.4]; multiplicative color changes to the RGB channels per image from [0.5, 2]; gamma values from [0.7,1.5] and additive brightness changes using Gaussian with a sigma of 0.2.

Thank you very much for your attention.

Regards

**Comment by twhui** [comment]
As shown in the prototxt file, data augmentation of LiteFlowNet and FlowNet2 are the same.

**Comment by abrosua** [comment]
Sorry, I think I look at the wrong FlowNet2 train prototxt, the FlowNet2-S and FlowNet2-CSS train prototxt do share the similarity with the LiteFlowNet's. Thanks for the reply.
