### ISSUE TITLE
Implementation of LiteFlowNet with tensorflow

### ISSUE THREAD

**Issue by keeper121** [twhui/LiteFlowNet#60]
Hi, @twhui. I try to implement LiteFlowNet's inference with tensorflow. I convert pretrained weights from https://github.com/sniklaus/pytorch-liteflownet (pytorch reimplementation). Seems it produce a bit different optical flow. I think it depends on difference in warping layer. But will be cool if you can add link to my repo.

Please take a look.
https://github.com/keeper121/liteflownet-tf2

**Comment by twhui** [comment]
Hi, @keeper121 . Thanks for your implementation of my work in tensorflow. I would suggest you to a link (https://github.com/twhui/LiteFlowNet#license-and-citation) for the licensing terms of my work.

The current implementation requires the conversion of trained model from Caffe to Pytorch and then to Tensorflow. Could you simply convert it from Caffe to Tensorflow?

**Comment by keeper121** [comment]
@twhui I added link to your license to readme. Also implemented separate converter for weights directly from Caffe to Tensorflow.

**Comment by twhui** [comment]
@keeper121  A link to your repo is added :).

**Comment by keeper121** [comment]
@twhui Thanks.
