### ISSUE TITLE
prepare lmdb file on kitti

### ISSUE THREAD

**Issue by lhao0301** [twhui/LiteFlowNet#61]
Wonderful work!

The code in `convert_imageset_and_flow.c` seems not to support the data format in kitti. Could you mind showing how to make lmdb file on kitti dataset because of the sparse optical flow?

**Comment by twhui** [comment]
The script convert_imageset_and_flow can handle sparse flow labels, but you need to explicitly introduce NaN into unlabeled pixels.

**Comment by lhao0301** [comment]
got & thanks!
