### ISSUE TITLE
Convert training.list and test.list issues make-lmdbs-train.sh

### ISSUE THREAD

**Issue by Crow77** [twhui/LiteFlowNet#62]
How do you create de training.list and the test.list from the downloaded dataset (e.g KITTI12) ?
I'm trying to run the make-lmdbs-train.sh script

Please help

**Comment by twhui** [comment]
You may need to write a script to read the filenames in your dataset and then write the filenames in train.list or test.list.

**Comment by Dang123** [comment]
You can create automatically by using the MATLAB software. I tried and succeeded to get file test.list and train.list.

**Comment by djy199301161819** [comment]
Hello, have you ever tried human face to do deep optical flow estimation? I'm trying to fuse optical flow with RBG for in vivo detection。Can you give me some help？

**Comment by twhui** [comment]
@djy199301161819  Are you working for a commercial product? Please note that the license term in this Github repo.

**Comment by Crow77** [comment]
No. It is for education purposes only

**Comment by Crow77** [comment]
Thanks a lot I finally create de list files and run the make-lmdbs-train.sh
