### ISSUE TITLE
about yout paper : Motion-Depth

### ISSUE THREAD

**Issue by RedOne88** [twhui/LiteFlowNet#67]
Hello,
just in relation to your paper: Motion-Depth: RGB-D Depth Map Enhancement with Motion and Depth in Complement
I am very interested in your work, I find it very relevant. I am working on this subject of filling holes on depth map by using motion detection(optical flow) on grayscale images.
Could you share the source code if it's possible.
Thank you in advance for your response.

**Comment by twhui** [comment]
Thank you for your interest in my research. Unfortunately, I lost the code package. Motion-Depth (CVPR 2014) was done by me more than 6 years ago!

**Comment by RedOne88** [comment]
OK no problem.
I am currently testing your method. I am in step "D", if I understood correctly, it is necessary to finish filling the matrix D_H before applying the equation "8"?if not for the neighborhood N4 it is indeed equal to N4 (p) = (D_H (i-1, j) + D_H (i + 1, j) + D_H (i, j-1) + D_H (i, j +1)) or should all neighborhoods be included (8 value instead of 4)?
thank you in advance
________________________________
De : Tak-Wai Hui ***@***.***>
Envoyé : dimanche 30 mai 2021 16:40
À : twhui/LiteFlowNet ***@***.***>
Cc : RedOne88 ***@***.***>; Author ***@***.***>
Objet : Re: [twhui/LiteFlowNet] about yout paper : Motion-Depth (#67)


Thank you for your interest in my research. Unfortunately, I lost the code package. Motion-Depth (CVPR 2014) was done by me more than 6 years ago!

**Comment by twhui** [comment]
What are step "D" and N4? I am unable to locate them in the paper.

**Comment by RedOne88** [comment]
you will find attached the relevant pape.
step D is the sub-section : D. Filling The Depth Map With Its Moving Object Areas And The Correspondent Boundary Protected
N_4(p) : is neighboring of pixel (p) in the sub-section D.
________________________________
De : Tak-Wai Hui ***@***.***>
Envoyé : mardi 1 juin 2021 07:45
À : twhui/LiteFlowNet ***@***.***>
Cc : RedOne88 ***@***.***>; Author ***@***.***>
Objet : Re: [twhui/LiteFlowNet] about yout paper : Motion-Depth (#67)


What are step "D" and N4? I am unable to locate them in the paper.

**Comment by twhui** [comment]
There is no "sub-section D" in <a href="https://openaccess.thecvf.com/content_cvpr_2014/papers/Hui_Motion-Depth_RGB-D_Depth_2014_CVPR_paper.pdf">the paper</a>.

**Comment by RedOne88** [comment]
sorry I got the paper wrong.
