### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by HuangJunJie2017** [twhui/LiteFlowNet#8]
will you develop a pytorch version of LiteFlowNet?  and beside,  i look forward to the prototex file of the network framework

**Comment by twhui** [comment]
@HuangJunJie2017 Hi JunJie. If you like my project, you can star this repository (https://help.github.com/articles/about-stars/).  I don't have the pytorch version at this moment. Maybe I can re-implement it in the future.

**Comment by sniklaus** [comment]
You can find a personal reimplementation here: https://github.com/sniklaus/pytorch-liteflownet

Thank you for sharing your implementation with us @twhui, I greatly appreciate it! I hope that a PyTorch version will help others better appreciate your work on LiteFlowNet, it definitely deserves more attention.

**Comment by HuangJunJie2017** [comment]
@sniklaus thanks!

**Comment by twhui** [comment]
@sniklaus Thanks for your contribution! I have added a link to your implementation :+1: .

**Comment by sniklaus** [comment]
Thank you for referencing it so prominently and I am looking forward to see LiteFlowNet thrive!
